name: jobs using containers
on: pull_request

jobs:
  node_js_container:
   runs-on: ubuntu-latest
   container: 
     image: node:19-alpine3.15
   steps:
     - name: Log version
       run: |
        node -v
        cat /etc/os-release