name: abc
on : pull_request

jobs:
  os-versions:
   strategy:
     matrix:
      os: [ubuntu-latest , macos-latest , windows-latest]
      node_version: [6, 8, 10]
      include:
       - os: ubuntu-latest
         node_version: 10
         included: "true"
      exclude: 
       - os: macos-latest 
         node_version: 6
     fail-fast: true
   runs-on: ${{ matrix.os }}
   env:
    INCLUDED: ${{ matrix.included }}
   steps:
    - name: Node version 
      run: node -v 
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version}}
    - name: New Node Version 
      run: |
       node -v
       echo $INCLUDED
    
      
      
     


  