name: abc
on : [push]

jobs:
  os-versions:
   strategy:
     matrix:
      os: [ubuntu-latest , macos-latest , windows-latest]
      node_version: [6, 8, 10]
     fail-fast: true
   runs-on: ${{ matrix.os }}
   steps:
    - name: Node version 
      run: node -v 
      
     


  