name: slack notify
on: pull_request

jobs:
  slack_notify:
   runs-on: ubuntu-latest
   steps:
     - name: slack 
       uses: docker://technosophos/slack-notify
       env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Hello from github action"
        
