name: Variable susbstitution
on: push

jobs:
  json_substitution:
   runs-on: ubuntu-latest
   steps:
     - uses: ./.github/actions
       with:
         source: ${{ env.source }}
         target: ${{ env.target }}